#ifndef _HARDWARE_SCSI_H
#define _HARDWARE_SCSI_H

/*
    Generic SCSI protocol constants shared by host adapters and the
    scsi.device frontend.
*/

#include <exec/types.h>

/* Bus phase encodings */
#define SCSI_PHASE_DATA_OUT      0x00
#define SCSI_PHASE_DATA_IN       0x01
#define SCSI_PHASE_COMMAND       0x02
#define SCSI_PHASE_STATUS        0x03
#define SCSI_PHASE_MESSAGE_OUT   0x06
#define SCSI_PHASE_MESSAGE_IN    0x07

/* SCSI status byte values */
#define SCSI_STATUS_GOOD             0x00
#define SCSI_STATUS_CHECK_CONDITION  0x02
#define SCSI_STATUS_CONDITION_MET    0x04
#define SCSI_STATUS_BUSY             0x08
#define SCSI_STATUS_INTERMEDIATE     0x10
#define SCSI_STATUS_INTERMEDIATE_COND_MET 0x14
#define SCSI_STATUS_RESERVATION_CONFLICT 0x18
#define SCSI_STATUS_COMMAND_TERMINATED   0x22
#define SCSI_STATUS_QUEUE_FULL       0x28

/* SCSI message codes */
#define SCSI_MESSAGE_COMMAND_COMPLETE    0x00
#define SCSI_MESSAGE_EXTENDED            0x01
#define SCSI_MESSAGE_SAVE_POINTERS       0x02
#define SCSI_MESSAGE_RESTORE_POINTERS    0x03
#define SCSI_MESSAGE_DISCONNECT          0x04
#define SCSI_MESSAGE_INITIATOR_ERROR     0x05
#define SCSI_MESSAGE_ABORT               0x06
#define SCSI_MESSAGE_MESSAGE_REJECT      0x07
#define SCSI_MESSAGE_NO_OP               0x08
#define SCSI_MESSAGE_MSG_PARITY_ERROR    0x09
#define SCSI_MESSAGE_LINKED_CMD_COMPLETE 0x0A
#define SCSI_MESSAGE_LINKED_CMD_COMPLETE_FLAG 0x0B
#define SCSI_MESSAGE_BUS_DEVICE_RESET    0x0C
#define SCSI_MESSAGE_ABORT_TAG           0x0D
#define SCSI_MESSAGE_CLEAR_QUEUE         0x0E
#define SCSI_MESSAGE_INITIATE_RECOVERY   0x0F
#define SCSI_MESSAGE_RELEASE_RECOVERY    0x10
#define SCSI_MESSAGE_TERMINATE_I_O       0x11
#define SCSI_MESSAGE_SIMPLE_QUEUE_TAG    0x20
#define SCSI_MESSAGE_HEAD_OF_QUEUE_TAG   0x21
#define SCSI_MESSAGE_ORDERED_QUEUE_TAG   0x22
#define SCSI_MESSAGE_IGNORE_QUEUE_TAG    0x23

/* Peripheral device types (as reported by INQUIRY) */
#define SCSI_DEVICE_DIRECT_ACCESS    0x00
#define SCSI_DEVICE_SEQUENTIAL       0x01
#define SCSI_DEVICE_PRINTER          0x02
#define SCSI_DEVICE_PROCESSOR        0x03
#define SCSI_DEVICE_WRITE_ONCE       0x04
#define SCSI_DEVICE_CDROM            0x05
#define SCSI_DEVICE_SCANNER          0x06
#define SCSI_DEVICE_OPTICAL          0x07
#define SCSI_DEVICE_MEDIUM_CHANGER   0x08
#define SCSI_DEVICE_COMMUNICATION    0x09
#define SCSI_DEVICE_ARRAY_CONTROLLER 0x0C
#define SCSI_DEVICE_ENCLOSURE        0x0D
#define SCSI_DEVICE_RBC              0x0E
#define SCSI_DEVICE_OCRW             0x0F
#define SCSI_DEVICE_BRIDGE           0x10
#define SCSI_DEVICE_OSD              0x11
#define SCSI_DEVICE_AUTOMATION       0x12
#define SCSI_DEVICE_RESERVED         0x1F

/* Sense key values */
#define SCSI_SENSE_KEY_NO_SENSE      0x00
#define SCSI_SENSE_KEY_RECOVERED     0x01
#define SCSI_SENSE_KEY_NOT_READY     0x02
#define SCSI_SENSE_KEY_MEDIUM_ERROR  0x03
#define SCSI_SENSE_KEY_HARDWARE_ERROR 0x04
#define SCSI_SENSE_KEY_ILLEGAL_REQUEST 0x05
#define SCSI_SENSE_KEY_UNIT_ATTENTION 0x06
#define SCSI_SENSE_KEY_DATA_PROTECT  0x07
#define SCSI_SENSE_KEY_BLANK_CHECK   0x08
#define SCSI_SENSE_KEY_VENDOR        0x09
#define SCSI_SENSE_KEY_COPY_ABORTED  0x0A
#define SCSI_SENSE_KEY_ABORTED       0x0B
#define SCSI_SENSE_KEY_VOLUME_OVERFLOW 0x0D
#define SCSI_SENSE_KEY_MISCOMPARE    0x0E

#endif /* _HARDWARE_SCSI_H */
